
obj-$(CONFIG_AURALIC_LEDS)      += auralic_leds.o
#obj-$(CONFIG_AURALIC_BUTTONS)   += auralic_buttons.o
obj-$(CONFIG_AURALIC_DAC)       += auralic_dac.o
obj-$(CONFIG_AURALIC_ISP)       += auralic_isp.o
obj-$(CONFIG_EXFAT_FS)			+= exfat/
obj-$(CONFIG_AURALIC_SND_USB_HIFACE)		+= snd-usb-asyncaudio-master/
obj-$(CONFIG_AURALIC_SND_USB_MYTEK)			+= mytekusb2-master/
